### ISSUE TITLE
Broken Navbar on Contacts and Product page

### ISSUE THREAD

**Issue by lukejohnlayson** [lukejohnlayson/AeroChess#1]
The navbar has not been applied to the product or contacts page.

**Comment by BetterSendBodyBags** [comment]
Hmm roger that. will do

**Comment by lukejohnlayson** [comment]
Fixed products page

**Comment by BetterSendBodyBags** [comment]
When are u coming ti the dorm today?

**Comment by BetterSendBodyBags** [comment]
Is it fixed? i am not sure if it has

**Comment by lukejohnlayson** [comment]
It's coloured black so just change it to the green we are using in the styles sheet. You may need to hunt for the contacts page header styling


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: BetterSendBodyBags <notifications@github.com> Date: 24/10/17  6:35 PM  (GMT+12:00) To: lukejohnlayson/AeroChess <AeroChess@noreply.github.com> Cc: lukejohnlayson <lukefin002@gmail.com>, Author <author@noreply.github.com> Subject: Re: [lukejohnlayson/AeroChess] Broken Navbar on Contacts and Product page (#1) 
Is it fixed? i am not sure if it has

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lukejohnlayson/AeroChess","title":"lukejohnlayson/AeroChess","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lukejohnlayson/AeroChess"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BetterSendBodyBags in #1: Is it fixed? i am not sure if it has "}],"action":{"name":"View Issue","url":"https://github.com/lukejohnlayson/AeroChess/issues/1#issuecomment-338879212"}}}
